#!/usr/bin/env python3
"""Print the M0 gate sequence without executing any gate.

This is a planner, not a runner. It exists so the controller can keep the
source-contract, acquisition, import-readiness, paper-contract, and truth
baseline gates in one ordered contract.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CONFIG = ROOT / "backend" / "config" / "m0_gates.yaml"


def load_gates(config_path: Path = DEFAULT_CONFIG) -> list[dict[str, Any]]:
    raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    gates = [dict(gate) for gate in raw.get("gates", [])]
    gates = sorted(gates, key=lambda gate: int(gate["order"]))
    validate_gates(gates)
    return gates


def validate_gates(gates: list[dict[str, Any]]) -> None:
    if not gates:
        raise ValueError("m0 gate config has no gates")

    orders = [int(gate.get("order", 0)) for gate in gates]
    expected_orders = list(range(1, len(gates) + 1))
    if orders != expected_orders:
        raise ValueError(f"m0 gate orders must be contiguous from 1: actual={orders}, expected={expected_orders}")

    names = [str(gate.get("name") or "") for gate in gates]
    duplicate_names = sorted({name for name in names if names.count(name) > 1})
    if duplicate_names:
        raise ValueError(f"duplicate m0 gate names: {duplicate_names}")

    required_fields = ("name", "command", "purpose", "expected_current_status", "failure_action")
    for gate in gates:
        missing = [field for field in required_fields if not str(gate.get(field) or "").strip()]
        if missing:
            raise ValueError(f"m0 gate {gate.get('order')} missing required fields: {missing}")
        for flag in ("writes_artifacts", "writes_db", "executes_external_fetch"):
            if not isinstance(gate.get(flag), bool):
                raise ValueError(f"m0 gate {gate.get('order')} field {flag} must be boolean")
        command = str(gate.get("command") or "")
        if "acquire_external_source.py" in command and "--reuse-existing" not in command and not gate["executes_external_fetch"]:
            raise ValueError(
                f"m0 gate {gate.get('order')} runs source acquisition without --reuse-existing "
                "but executes_external_fetch is false"
            )


def _markdown(gates: list[dict[str, Any]]) -> str:
    lines = [
        "# M0 Gate Plan",
        "",
        "This file is generated by `scripts/tools/audit/m0_gate_plan.py`.",
        "The script prints the plan only; it does not execute gates.",
        "",
        "| # | Gate | Command | Writes artifacts | Writes DB | External fetch | Expected current status | Failure action |",
        "|---:|---|---|---|---|---|---|---|",
    ]
    for gate in gates:
        lines.append(
            f"| {gate['order']} | `{gate['name']}` | `{gate['command']}` | "
            f"{str(gate.get('writes_artifacts')).lower()} | "
            f"{str(gate.get('writes_db')).lower()} | "
            f"{str(gate.get('executes_external_fetch')).lower()} | "
            f"{gate['expected_current_status']} | {gate['failure_action']} |"
        )
    return "\n".join(lines) + "\n"


def _json(gates: list[dict[str, Any]], config_path: Path) -> str:
    risk_summary = {
        "writes_artifacts": [gate["name"] for gate in gates if gate.get("writes_artifacts")],
        "writes_db": [gate["name"] for gate in gates if gate.get("writes_db")],
        "executes_external_fetch": [gate["name"] for gate in gates if gate.get("executes_external_fetch")],
    }
    payload: dict[str, Any] = {
        "tool": "scripts/tools/audit/m0_gate_plan.py",
        "config": str(config_path),
        "executes_gates": False,
        "writes_artifacts": bool(risk_summary["writes_artifacts"]),
        "writes_db": bool(risk_summary["writes_db"]),
        "executes_external_fetch": bool(risk_summary["executes_external_fetch"]),
        "risk_summary": {
            "writes_artifacts_count": len(risk_summary["writes_artifacts"]),
            "writes_db_count": len(risk_summary["writes_db"]),
            "executes_external_fetch_count": len(risk_summary["executes_external_fetch"]),
            **risk_summary,
        },
        "gates": gates,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    gates = load_gates(args.config)
    text = _markdown(gates) if args.format == "markdown" else _json(gates, args.config)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
